version = 1

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["Bootstrap4"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angularjs",
    "angular"
  ]
  environment = [
    "nodejs",
    "jquery"
  ]